In [1]:
import numpy as np


In [37]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [50]:
B = np.hsplit(A, [2])
[A.shape, len(B)]

[(2, 3), 2]

In [51]:
B

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [60]:
C = np.hstack([A, np.ones(A.shape[0])[:,None]])

In [61]:
C.shape

(2, 4)

In [62]:
np.dot([1, 2, 3], [2, 3, 4])

20

In [71]:
x = np.array([[1], [2], [3]]).reshape(1,3)[0]
y = np.array([[4], [5], [6]]).reshape(1,3)[0]

In [72]:
np.dot(x, y)

32

In [106]:
P = np.array("15  12  8   8   7   7   7   6   5   3".split(), dtype=float)
H = np.array("10  25  17  11  13  17  20  13  9   15".split(), dtype=float)

In [107]:
(P, H)

(array([15., 12.,  8.,  8.,  7.,  7.,  7.,  6.,  5.,  3.]),
 array([10., 25., 17., 11., 13., 17., 20., 13.,  9., 15.]))

In [108]:
ones = np.ones((len(P), 1))
P1 = np.append(P[:,None], ones, axis=1)
P1.shape


(10, 2)

In [110]:
coef = np.linalg.lstsq(P1, H)[0]

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [111]:
np.dot(np.array([10, 1]), coef)

15.458333333333329

In [117]:
h = np.dot(P1, coef)
resid = H - h
np.mean(resid)
coef

array([ 0.20833333, 13.375     ])