In [2]:
import numpy as np
import torch

arr = [[1,2], [3,4]]
np.array(arr)
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [2]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [3]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [4]:
torch.rand(2, 2)

tensor([[0.1075, 0.6047],
        [0.2485, 0.9703]])

In [5]:
torch.cuda.is_available()

True

In [11]:
nparr = np.ones((2,2), dtype=np.float32)

In [12]:
torch_tensor = torch.from_numpy(nparr)

In [13]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [14]:
torch_tensor.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [15]:
torch_tensor.cpu()
torch_tensor.cuda()

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [16]:
torch_tensor.view(4)

tensor([1., 1., 1., 1.])

In [17]:
torch.ones((2,2)) + torch.ones((2,2))

tensor([[2., 2.],
        [2., 2.]])

In [19]:
a = torch.ones((2,2))
b = torch.ones((2,2))
a.add_(b)
a

tensor([[2., 2.],
        [2., 2.]])

In [21]:
a = torch.Tensor([range(10), range(10)])
a.mean(dim=1)

tensor([4.5000, 4.5000])

In [5]:
from torch.autograd import Variable
a = Variable(torch.ones((2,2)), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)